//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 04:54:50 PM EET 
//


package XML.ModleXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fontFamily.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fontFamily">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="cursive"/>
 *     &lt;enumeration value="sans-serif"/>
 *     &lt;enumeration value="three"/>
 *     &lt;enumeration value="four"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "fontFamily")
@XmlEnum
public enum FontFamily {

    @XmlEnumValue("cursive")
    CURSIVE("cursive"),
    @XmlEnumValue("sans-serif")
    SANS_SERIF("sans-serif"),
    @XmlEnumValue("three")
    THREE("three"),
    @XmlEnumValue("four")
    FOUR("four");
    private final String value;

    FontFamily(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FontFamily fromValue(String v) {
        for (FontFamily c: FontFamily.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
